#!/usr/bin/env bash
# Push the generated Homebrew formula + Scoop manifest to the tap repos.
#
# Requires (env):
#   VERSION    the version being published (e.g. 0.22.0)
#   TAP_TOKEN  a fine-grained PAT with contents:write on wavyx/homebrew-tap and
#              wavyx/scoop-pdcli. Absent -> this script no-ops (never fails).
# Requires (files): packaging/homebrew/pdcli.rb + packaging/scoop/pdcli.json,
#   already generated by `node scripts/gen-dist.mjs "$VERSION"`.
#
# Shared by the release workflow (auto on tag) and the manual publish-dist
# workflow, so the two can never drift.
set -euo pipefail

: "${VERSION:?VERSION required}"

# A prerelease must never move the stable formula/manifest.
case "$VERSION" in
  *-*) echo "prerelease $VERSION — skipping tap publish"; exit 0 ;;
esac

if [ -z "${TAP_TOKEN:-}" ]; then
  echo "No TAP_TOKEN — skipping Homebrew/Scoop publish."
  echo "Add the PAT secret, or run 'node scripts/gen-dist.mjs $VERSION' and push manually."
  exit 0
fi

git config --global user.name "pdcli-release"
git config --global user.email "release@wavyx.dev"

push_file() {
  repo="$1"; src="$2"; dest="$3"
  tmp="$(mktemp -d)"
  git clone --depth 1 "https://x-access-token:${TAP_TOKEN}@github.com/${repo}.git" "$tmp"
  mkdir -p "$(dirname "$tmp/$dest")"
  cp "$src" "$tmp/$dest"
  git -C "$tmp" add "$dest"
  if git -C "$tmp" commit -m "pdcli $VERSION"; then
    git -C "$tmp" push
    echo "pushed $repo/$dest"
  else
    echo "no change for $repo/$dest"
  fi
}

push_file wavyx/homebrew-tap packaging/homebrew/pdcli.rb Formula/pdcli.rb
push_file wavyx/scoop-pdcli packaging/scoop/pdcli.json bucket/pdcli.json
